apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.com/ayush-sharma/example-assets.git
    path: argocd/my-apps/app-1
    targetRevision: HEAD
